# Generated by Django 5.0.6 on 2024-07-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_like_users'),
        ('teams', '0006_alter_task_manager'),
    ]

    operations = [
    ]
